[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"